-- Generated by the database client.
CREATE TABLE ref_join_formation_voeu(
    id_formation varchar(255) NOT NULL,
    id_voeu varchar(255) NOT NULL,
    CONSTRAINT fk_ref_join_formation_voeu_id_formation FOREIGN key(id_formation) REFERENCES ref_formation(id),
    CONSTRAINT fk_ref_join_formation_voeu_id_voeu FOREIGN key(id_voeu) REFERENCES ref_voeu(id)
);