CREATE TABLE trace (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_eleve VARCHAR(200) NOT NULL,
    tsp TIMESTAMP NOT NULL,
    action VARCHAR(255) NOT NULL,
    param1 VARCHAR(255) NULL,
    param2 VARCHAR(255) NULL
);

COMMENT ON TABLE trace IS 'traces de navigation';
COMMENT ON COLUMN trace.id IS 'id';

CREATE INDEX idx_trace_id_eleve ON trace(id_eleve);

--
-- Name: sugg_candidats_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE trace_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
