spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

flyway.url=${DB_URL}
flyway.user=${DB_USER}
flyway.password=${DB_PASSWORD}

dataRootDirectory=${MPS_DATA_DIR:/mps/data}

spring.jpa.hibernate.ddl-auto=none

# Enable SQL logging
logging.level.org.hibernate=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type=WARN
# Configure batch size
spring.jpa.properties.hibernate.jdbc.batch_size=1000
# Enable ordering of inserts to optimize batch processing
spring.jpa.properties.hibernate.order_inserts=true
# Enable ordering of updates to optimize batch processing
spring.jpa.properties.hibernate.order_updates=true

flyway.enabled=true
flyway.locations=classpath:db/migration
flyway.baselineOnMigrate=true

# repertoire de donnees qui contient data

mps.minimalTestDataSet=false


mps.data.avenirs.api.use-api=${MPS_DATA_AVENIRS_API_USE_API:false}
mps.data.avenirs.api.client-secret=${MPS_DATA_AVENIRS_API_CLIENT_SECRET:}
mps.data.avenirs.api.client-id=${MPS_DATA_AVENIRS_API_CLIENT_ID:}
mps.data.avenirs.api.access_token_uri=${MPS_DATA_AVENIRS_API_ACCESS_TOKEN_URI:}
mps.data.avenirs.api.indicateurs.eleves.endpoint=${MPS_DATA_AVENIRS_API_INDICATEURS_ELEVES_ENDPOINT:}
mps.data.avenirs.api.indicateurs.eleves.outil-id=${MPS_DATA_AVENIRS_API_INDICATEURS_ELEVES_OUTIL_ID:}
mps.data.avenirs.api.indicateurs.eleves.activite-id=${MPS_DATA_AVENIRS_API_INDICATEURS_ELEVES_ACTIVITE_ID:}

mps.data.avenirs.api.baseurl=${MPS_DATA_AVENIRS_API_BASEURL:}
mps.data.avenirs.api.metiers.uri=${MPS_DATA_AVENIRS_API_METIERS_ENDPOINT:}

mps.data.google.use-api=${MPS_DATA_GOOGLE_USE_API:false}
mps.data.google.api.uri=https://sheets.googleapis.com/v4/spreadsheets
mps.data.google.api.key=${MPS_DATA_GOOGLE_API_KEY:}
mps.data.google.api.spreadsheet-id=${MPS_DATA_GOOGLE_API_SPREADSHEET_ID:}

mps.data.ideo.od.formations.fiches.uri=https://api.opendata.onisep.fr/downloads/5fe07a9ecc960/5fe07a9ecc960.zip
mps.data.ideo.od.formations.simple.uri=https://api.opendata.onisep.fr/downloads/5fa591127f501/5fa591127f501.json
mps.data.ideo.od.metiers.simple.uri=https://api.opendata.onisep.fr/downloads/5fa5949243f97/5fa5949243f97.json
mps.data.ideo.od.metiers.fiches.uri=https://api.opendata.onisep.fr/downloads/5fe0808a2da6f/5fe0808a2da6f.zip
mps.data.ideo.od.domaines.uri=https://api.opendata.onisep.fr/downloads/5fa58d750a60c/5fa58d750a60c.json

mps.data.reference.table.expert=profil_reference_expert
mps.data.reference.table.lyceen=profil_reference_lyceen


spring.config.import=optional:secrets.properties