package fr.gouv.monprojetsup.metier.application.controller

import fr.gouv.monprojetsup.commun.application.dto.LienDTO
import fr.gouv.monprojetsup.metier.application.dto.MetierCourtDTO
import fr.gouv.monprojetsup.metier.application.dto.MetierDTO
import fr.gouv.monprojetsup.metier.application.dto.MetiersCourtsDTO
import fr.gouv.monprojetsup.metier.application.dto.MetiersDTO
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController

@RequestMapping("api/v1/metiers")
@RestController
class MetierController {
    @GetMapping("/recherche/succincte")
    fun getRechercheMetierSuccincte(
        @RequestParam recherche: String,
    ): MetiersCourtsDTO {
        val metiers = listOf(
            MetierCourtDTO(id = "MET_392", "ergonome du sport"),
            MetierCourtDTO(id = "MET_394", "sculpteur / sculptrice sur bois"),
            MetierCourtDTO(id = "MET_396", "administrateur / administratrice de biens"),
            MetierCourtDTO(id = "MET_395", "antiquaire"),
            MetierCourtDTO(id = "MET_398", "agent / agente de transit"),
            MetierCourtDTO(id = "MET_397", "analyste financier / financière"),
            MetierCourtDTO(id = "MET_390", "technicien / technicienne frigoriste"),
            MetierCourtDTO(id = "MET_399", "consignataire de navire"),
            MetierCourtDTO(id = "MET_370", "ingénieur / ingénieure essais"),
            MetierCourtDTO(id = "MET_372", "écotoxicologue"),
            MetierCourtDTO(id = "MET_371", "aérodynamicien / aérodynamicienne en aéronautique"),
            MetierCourtDTO(id = "MET_374", "architecte du patrimoine"),
            MetierCourtDTO(id = "MET_373", "infirmier/ère de bloc opératoire"),
            MetierCourtDTO(id = "MET_375", "masseur-kinésithérapeute (sport)"),
            MetierCourtDTO(id = "MET_381", "directeur/trice de collection"),
            MetierCourtDTO(id = "MET_385", "journaliste sportive"),
            MetierCourtDTO(id = "MET_384", "technicien / technicienne packaging"),
            MetierCourtDTO(id = "MET_389", "designer d'espaces publics"),
            MetierCourtDTO(id = "MET_388", "technicien/ne essais sol sur aéronef"),
            MetierCourtDTO(id = "MET_350", "chef / cheffe de station de traitement des eaux"),
            MetierCourtDTO(id = "MET_7803", "agent/e de sécurité incendie"),
            MetierCourtDTO(id = "MET_352", "yield manager"),
            MetierCourtDTO(id = "MET_351", "ingénieur / ingénieure métallurgiste"),
            MetierCourtDTO(id = "MET_354", "traducteur/trice technique"),
            MetierCourtDTO(id = "MET_353", "responsable e-CRM"),
            MetierCourtDTO(id = "MET_356", "ingénieur / ingénieure matériaux"),
            MetierCourtDTO(id = "MET_355", "responsable de laboratoire de contrôle en chimie"),
            MetierCourtDTO(id = "MET_358", "pilote d'hélicoptère"),
            MetierCourtDTO(id = "MET_357", "électromécanicien/ne en remontées mécaniques"),
            MetierCourtDTO(id = "MET_359", "régisseur / régisseuse lumière"),
            MetierCourtDTO(
                id = "MET_361",
                "psychologue de l'Éducation nationale spécialité éducation, développement et apprentissages",
            ),
            MetierCourtDTO(id = "MET_362", "responsable d'élevage agricole"),
            MetierCourtDTO(id = "MET_367", "chef / cheffe de projet sites et sols pollués"),
            MetierCourtDTO(id = "MET_366", "physicien médical / physicienne médicale"),
            MetierCourtDTO(id = "MET_369", "pédologue"),
            MetierCourtDTO(id = "MET_368", "ingénieur/e environnement et risques industriels"),
            MetierCourtDTO(id = "MET_332", "chirurgien/ne"),
            MetierCourtDTO(id = "MET_331", "correcteur / correctrice"),
            MetierCourtDTO(id = "MET_334", "rédacteur/trice on line"),
            MetierCourtDTO(id = "MET_333", "juriste en propriété intellectuelle"),
            MetierCourtDTO(id = "MET_336", "gardien / gardienne de la paix"),
            MetierCourtDTO(id = "MET_335", "pédiatre"),
            MetierCourtDTO(id = "MET_338", "consultant/e web analytique"),
            MetierCourtDTO(id = "MET_337", "géologue minier / minière"),
            MetierCourtDTO(id = "MET_341", "conseiller / conseillère en génétique"),
            MetierCourtDTO(id = "MET_340", "chargé/e de veille législative et réglementaire"),
            MetierCourtDTO(id = "MET_343", "infirmier/ère humanitaire"),
            MetierCourtDTO(id = "MET_342", "conseiller / conseillère en insertion sociale et professionnelle"),
            MetierCourtDTO(id = "MET_345", "moniteur/trice d'activités équestres"),
            MetierCourtDTO(id = "MET_344", "médecin humanitaire"),
            MetierCourtDTO(id = "MET_347", "agent / agente de sécurité"),
            MetierCourtDTO(id = "MET_346", "salesman"),
            MetierCourtDTO(id = "MET_349", "ingénieur / ingénieure hydroécologue"),
            MetierCourtDTO(id = "MET_348", "chargé / chargée d'affaires en génie mécanique"),
            MetierCourtDTO(id = "MET_310", "orfèvre"),
            MetierCourtDTO(id = "MET_319", "<span>Assistant / assistante de direction</span>"),
            MetierCourtDTO(id = "MET_312", "moniteur/trice de ski"),
            MetierCourtDTO(id = "MET_311", "éducateur spécialisé / éducatrice spécialisée"),
            MetierCourtDTO(id = "MET_314", "chargé / chargée des relations publiques"),
            MetierCourtDTO(id = "MET_316", "concepteur-rédacteur / conceptrice-rédactrice"),
            MetierCourtDTO(id = "MET_315", "mixeur / mixeuse son"),
            MetierCourtDTO(id = "MET_318", "façonnier / façonnière des industries graphiques"),
            MetierCourtDTO(id = "MET_317", "vendeur-magasinier / vendeuse-magasinière en fournitures automobiles"),
            MetierCourtDTO(id = "MET_321", "technicien / technicienne d'exploitation de l'eau"),
            MetierCourtDTO(id = "MET_322", "miroitier / miroitier"),
            MetierCourtDTO(id = "MET_325", "ingénieur / ingénieure nucléaire"),
            MetierCourtDTO(id = "MET_324", "mécanicien/ne de maintenance des matériels agricoles ou d'espaces verts"),
            MetierCourtDTO(id = "MET_327", "audiodescripteur / audiodescriptrice"),
            MetierCourtDTO(id = "MET_326", "ingénieur / ingénieure en automatismes"),
            MetierCourtDTO(id = "MET_329", "expert / experte en assurances"),
            MetierCourtDTO(id = "MET_328", "consultant/e SaaS"),
            MetierCourtDTO(id = "MET_309", "céramiste"),
            MetierCourtDTO(id = "MET_308", "étalagiste"),
            MetierCourtDTO(id = "MET_301", "secrétaire des Affaires étrangères"),
            MetierCourtDTO(id = "MET_300", "attaché / attachée de recherche clinique"),
            MetierCourtDTO(id = "MET_303", "ingénieur / ingénieure R&D en énergies renouvelables"),
            MetierCourtDTO(id = "MET_302", "chef / cheffe de projet éolien"),
            MetierCourtDTO(id = "MET_305", "opérateur / opératrice de raffinerie"),
            MetierCourtDTO(id = "MET_304", "ingénieur / ingénieure gaz"),
            MetierCourtDTO(id = "MET_307", "éclairagiste"),
            MetierCourtDTO(id = "MET_306", "dessinateur / dessinatrice en construction mécanique"),
            MetierCourtDTO(id = "MET_507", "coloriste (papier-carton)"),
            MetierCourtDTO(id = "MET_506", "technicien réalisateur / technicienne réalisatrice radio"),
            MetierCourtDTO(id = "MET_509", "agent / agente d'exploitation de l'eau"),
            MetierCourtDTO(id = "MET_501", "chargé / chargée de référencement web"),
            MetierCourtDTO(id = "MET_500", "ingénieur/e efficacité énergétique du bâtiment"),
            MetierCourtDTO(id = "MET_503", "développeur/euse d'applications mobiles"),
            MetierCourtDTO(id = "MET_502", "ingénieur/e procédés en chimie"),
            MetierCourtDTO(id = "MET_505", "auditeur/trice vert/e HSE"),
            MetierCourtDTO(id = "MET_504", "<span>Mannequin</span>"),
            MetierCourtDTO(id = "MET_491", "ingénieur / ingénieure de maintenance industrielle"),
            MetierCourtDTO(id = "MET_490", "chef / cheffe de projet web-mobile"),
            MetierCourtDTO(id = "MET_493", "motard/e de la police ou de la gendarmerie"),
            MetierCourtDTO(id = "MET_492", "ingénieur/e qualité moteur"),
            MetierCourtDTO(id = "MET_497", "réflexologue"),
            MetierCourtDTO(id = "MET_499", "ingénieur/e méthodes mécaniques"),
            MetierCourtDTO(id = "MET_498", "chargé / chargée d'études de prix"),
            MetierCourtDTO(id = "MET_471", "entraîneur / entraîneuse de chevaux"),
            MetierCourtDTO(id = "MET_470", "technicien / technicienne télécoms et réseaux"),
            MetierCourtDTO(id = "MET_473", "chargé / chargée de projet événementiel"),
            MetierCourtDTO(id = "MET_472", "juge des enfants"),
            MetierCourtDTO(id = "MET_475", "géochimiste"),
            MetierCourtDTO(id = "MET_474", "ingénieur/e électronicien/ne des systèmes de la sécurité aérienne (IESSA)"),
            MetierCourtDTO(id = "MET_477", "<span>écrivain / écrivaine public</span>"),
            MetierCourtDTO(id = "MET_476", "<span>Réalisateur / réalisatrice de films</span>"),
            MetierCourtDTO(id = "MET_479", "assistant maternel / assistante maternelle"),
            MetierCourtDTO(id = "MET_478", "architecte des systèmes d'information"),
            MetierCourtDTO(id = "MET_480", "ingénieur/e textile"),
            MetierCourtDTO(id = "MET_482", "expert immobilier / experte immobilier"),
            MetierCourtDTO(id = "MET_481", "entraîneur/euse sportif/ve"),
            MetierCourtDTO(id = "MET_484", "convoyeur/euse de fonds"),
            MetierCourtDTO(id = "MET_483", "souscripteur / souscriptrice"),
            MetierCourtDTO(id = "MET_486", "responsable de plate-forme biotechnologique"),
            MetierCourtDTO(id = "MET_485", "chargé / chargée de recherche et développement déchets"),
            MetierCourtDTO(id = "MET_488", "ingénieur / ingénieure combustion et brûleurs"),
            MetierCourtDTO(id = "MET_487", "responsable biométrie"),
            MetierCourtDTO(id = "MET_489", "traffic manager"),
            MetierCourtDTO(id = "MET_451", "conseiller / conseillère en séjour"),
            MetierCourtDTO(id = "MET_450", "webdesigner"),
            MetierCourtDTO(id = "MET_453", "commercial / commerciale export"),
            MetierCourtDTO(id = "MET_452", "régisseur / régisseuse de spectacles"),
            MetierCourtDTO(id = "MET_455", "dessinateur-projeteur / dessinatrice-projeteuse"),
            MetierCourtDTO(id = "MET_454", "garde à cheval"),
            MetierCourtDTO(id = "MET_457", "consultant / consultante"),
            MetierCourtDTO(id = "MET_456", "staffeur/euse-ornemaniste"),
            MetierCourtDTO(id = "MET_459", "expert / experte en sécurité informatique"),
            MetierCourtDTO(id = "MET_458", "credit manager"),
            MetierCourtDTO(id = "MET_460", "ingénieur / ingénieure en métrologie"),
            MetierCourtDTO(id = "MET_462", "technicien / technicienne en métrologie"),
            MetierCourtDTO(id = "MET_461", "statisticien / statisticienne"),
            MetierCourtDTO(id = "MET_464", "directeur/trice de golf"),
            MetierCourtDTO(id = "MET_463", "écrivain / écrivaine"),
            MetierCourtDTO(id = "MET_466", "nivoculteur / nivocultrice"),
            MetierCourtDTO(id = "MET_465", "généticien/ne"),
            MetierCourtDTO(id = "MET_468", "économètre statisticien / statisticienne"),
            MetierCourtDTO(id = "MET_469", "administrateur / administratrice de spectacle"),
            MetierCourtDTO(id = "MET_431", "professeur / professeure de lycée professionnel"),
            MetierCourtDTO(id = "MET_430", "mécanicien / mécanicienne en engins de travaux publics"),
            MetierCourtDTO(id = "MET_433", "ingénieur / ingénieure environnement"),
            MetierCourtDTO(id = "MET_432", "acheteur / acheteuse d'espaces publicitaires"),
            MetierCourtDTO(id = "MET_435", "carreleur / carreleuse-mosaïste"),
            MetierCourtDTO(id = "MET_434", "directeur / directrice d'office de tourisme"),
            MetierCourtDTO(id = "MET_436", "électromécanicien / électromécanicienne"),
            MetierCourtDTO(id = "MET_439", "menuisier / menuisière"),
            MetierCourtDTO(id = "MET_438", "chef / cheffe de chantier"),
            MetierCourtDTO(id = "MET_440", "parfumeur / parfumeuse"),
            MetierCourtDTO(id = "MET_442", "conseiller / conseillère espace info-énergie"),
            MetierCourtDTO(id = "MET_441", "attaché territorial / attachée territoriale"),
            MetierCourtDTO(id = "MET_443", "géothermicien / géothermicienne"),
            MetierCourtDTO(id = "MET_446", "costumier / costumière"),
            MetierCourtDTO(id = "MET_445", "animateur / animatrice du patrimoine"),
            MetierCourtDTO(id = "MET_448", "esthéticien-cosméticien / esthéticienne-cosméticienne"),
            MetierCourtDTO(id = "MET_447", "bottier / bottière"),
            MetierCourtDTO(id = "MET_449", "linguiste"),
            MetierCourtDTO(id = "MET_419", "médecin spécialiste"),
            MetierCourtDTO(id = "MET_418", "visiteur médical / visiteuse médicale"),
            MetierCourtDTO(id = "MET_411", "prothésiste dentaire"),
            MetierCourtDTO(id = "MET_410", "contrôleur / contrôleuse de gestion"),
            MetierCourtDTO(id = "MET_413", "océanologue"),
            MetierCourtDTO(id = "MET_412", "pharmacien industriel / pharmacienne industrielle"),
            MetierCourtDTO(id = "MET_414", "ethnologue"),
            MetierCourtDTO(id = "MET_417", "ambulancier / ambulancière"),
            MetierCourtDTO(id = "MET_416", "manipulateur / manipulatrice en électroradiologie médicale"),
            MetierCourtDTO(id = "MET_420", "cuisinier / cuisinière"),
            MetierCourtDTO(id = "MET_429", "responsable de scierie"),
            MetierCourtDTO(id = "MET_422", "webmestre"),
            MetierCourtDTO(id = "MET_421", "scripte"),
            MetierCourtDTO(id = "MET_424", "botaniste"),
            MetierCourtDTO(id = "MET_423", "professeur / professeure dans l'enseignement agricole"),
            MetierCourtDTO(id = "MET_426", "conducteur opérateur / conductrice opératrice de scierie"),
            MetierCourtDTO(id = "MET_425", "cordonnier / cordonnière"),
            MetierCourtDTO(id = "MET_428", "agronome"),
            MetierCourtDTO(id = "MET_427", "officier marinier / officière marinière"),
            MetierCourtDTO(id = "MET_408", "géomètre-topographe"),
            MetierCourtDTO(id = "MET_407", "urbaniste"),
            MetierCourtDTO(id = "MET_409", "agent général / agente générale d'assurances"),
            MetierCourtDTO(id = "MET_400", "pilote de ligne"),
            MetierCourtDTO(id = "MET_402", "microtechnicien / microtechnicienne"),
            MetierCourtDTO(id = "MET_401", "ingénieur / ingénieure en mécanique"),
            MetierCourtDTO(id = "MET_404", "électronicien / électronicienne automobile"),
            MetierCourtDTO(id = "MET_403", "technicien électrotechnicien / technicienne électrotechnicienne"),
            MetierCourtDTO(id = "MET_406", "opérateur / opératrice prépresse"),
            MetierCourtDTO(id = "MET_405", "agenceur/euse de cuisines et salles de bains"),
            MetierCourtDTO(id = "MET_617", "ingénieur/e process aval"),
            MetierCourtDTO(id = "MET_616", "chargé / chargée d'études en valorisation agricole des déchets"),
            MetierCourtDTO(id = "MET_7812", "maître-chien"),
            MetierCourtDTO(id = "MET_619", "gestionnaire de contrats informatiques"),
            MetierCourtDTO(id = "MET_7813", "documentariste"),
            MetierCourtDTO(id = "MET_7814", "animateur / animatrice de site web"),
            MetierCourtDTO(id = "MET_618", "chargé / chargée des méthodes outils et qualité en informatique"),
            MetierCourtDTO(id = "MET_7819", "assistant médical / assistante médicale"),
            MetierCourtDTO(id = "MET_611", "architecte produit industriel"),
            MetierCourtDTO(id = "MET_610", "chargé / chargée d'études naturalistes"),
            MetierCourtDTO(id = "MET_613", "data manager"),
            MetierCourtDTO(id = "MET_7815", "musicien intervenant / musicienne intervenante"),
            MetierCourtDTO(id = "MET_612", "ingénieur/e traitement de l'image"),
            MetierCourtDTO(id = "MET_7817", "éducateur/trice de chiens guides d'aveugles"),
            MetierCourtDTO(id = "MET_615", "substitut/e du procureur"),
            MetierCourtDTO(id = "MET_614", "collecteur / collectrice de fonds"),
            MetierCourtDTO(id = "MET_7818", "agent / agente valoriste"),
            MetierCourtDTO(id = "MET_628", "responsable de fabrication en chimie"),
            MetierCourtDTO(id = "MET_627", "statisticien/ne industriel/le"),
            MetierCourtDTO(id = "MET_620", "halieute"),
            MetierCourtDTO(id = "MET_622", "consultant/e informatique"),
            MetierCourtDTO(id = "MET_621", "designer sonore"),
            MetierCourtDTO(id = "MET_624", "consultant/e en conduite de changement"),
            MetierCourtDTO(id = "MET_623", "spécialiste de l'accessibilité numérique"),
            MetierCourtDTO(id = "MET_626", "ingénieur/e d'études en sûreté nucléaire"),
            MetierCourtDTO(id = "MET_625", "responsable achats en chimie"),
            MetierCourtDTO(id = "MET_606", "fiscaliste"),
            MetierCourtDTO(id = "MET_605", "horloger / horlogère"),
            MetierCourtDTO(id = "MET_607", "hydrogéologue"),
            MetierCourtDTO(id = "MET_600", "poissonnier / poissonnière"),
            MetierCourtDTO(id = "MET_602", "ingénieur / ingénieure en imagerie médicale"),
            MetierCourtDTO(id = "MET_604", "conseiller / conseillère en voyages"),
            MetierCourtDTO(id = "MET_603", "ingénieur / ingénieure frigoriste"),
            MetierCourtDTO(id = "MET_7860", "pharmacien/ne distributeur/trice en gros"),
            MetierCourtDTO(id = "MET_7855", "addictologue"),
            MetierCourtDTO(id = "MET_7856", "gérontopsychiatre"),
            MetierCourtDTO(id = "MET_7857", "pédopsychiatre"),
            MetierCourtDTO(id = "MET_7858", "pharmacien chercheur / pharmacienne chercheuse"),
            MetierCourtDTO(id = "MET_7852", "responsable d'un centre de compostage"),
            MetierCourtDTO(id = "MET_7859", "pharmacien hospitalier / pharmacienne hospitalière"),
            MetierCourtDTO(id = "MET_7833", "<span>Kiosquier / kiosquière</span>"),
            MetierCourtDTO(
                id = "MET_7834",
                "<span>Artiste graffeur professionnel /</span> <br> <span>artiste graffeuse professionnelle</span>",
            ),
            MetierCourtDTO(id = "MET_7835", "<span>Astronaute</span>"),
            MetierCourtDTO(id = "MET_7836", "<span>Influenceur / influenceuse</span>"),
            MetierCourtDTO(id = "MET_594", "vendeur / vendeuse en micro-informatique et multimédia"),
            MetierCourtDTO(
                id = "MET_7830",
                "<span>Adjoint / adjointe technique</span> <br> <span>des établissements d'enseignement</span>",
            ),
            MetierCourtDTO(id = "MET_7831", "<span>Assistant / assistante d'éducation</span>"),
            MetierCourtDTO(id = "MET_7832", "<span>Chef / cheffe d'établissement</span> <br> <span>scolaire</span>"),
            MetierCourtDTO(id = "MET_7837", "technicien / technicienne valoriste"),
            MetierCourtDTO(id = "MET_7820", "médecin urgentiste"),
            MetierCourtDTO(id = "MET_7821", "agent / agente d'opérations aériennes"),
            MetierCourtDTO(id = "MET_7829", "accompagnant/e d'élèves en situation de handicap"),
            MetierCourtDTO(id = "MET_590", "chercheur / chercheuse en chimie"),
            MetierCourtDTO(id = "MET_592", "cogniticien / cogniticienne"),
            MetierCourtDTO(id = "MET_591", "auditeur / auditrice externe"),
            MetierCourtDTO(id = "MET_593", "formateur/trice en informatique"),
            MetierCourtDTO(id = "MET_596", "mécanicien / mécanicienne marine navigant"),
            MetierCourtDTO(id = "MET_595", "décolleteur / décolleteuse"),
            MetierCourtDTO(id = "MET_598", "ingénieur / ingénieure de la police technique et scientifique"),
            MetierCourtDTO(id = "MET_597", "agent / agente d'escale"),
            MetierCourtDTO(id = "MET_599", "consultant/e en solutions intégrées"),
            MetierCourtDTO(id = "MET_570", "géologue"),
            MetierCourtDTO(id = "MET_571", "acheteur / acheteuse"),
            MetierCourtDTO(id = "MET_574", "technicien / technicienne d'essais"),
            MetierCourtDTO(id = "MET_573", "monteur / monteuse en réseaux de distribution électrique"),
            MetierCourtDTO(id = "MET_576", "chaudronnier / chaudronnière"),
            MetierCourtDTO(id = "MET_575", "ajusteur-monteur / ajusteuse-monteuse"),
            MetierCourtDTO(id = "MET_578", "adjoint administratif / adjointe administrative"),
            MetierCourtDTO(id = "MET_577", "batelier / batelière"),
            MetierCourtDTO(id = "MET_581", "relieur-doreur / relieuse-doreuse"),
            MetierCourtDTO(id = "MET_580", "responsable de projets culturels"),
            MetierCourtDTO(id = "MET_583", "iconographe"),
            MetierCourtDTO(id = "MET_582", "animateur / animatrice de radio et de télévision"),
            MetierCourtDTO(id = "MET_585", "ingénieur / ingénieure du son"),
            MetierCourtDTO(id = "MET_584", "auteur-compositeur interprète / auteure-compositrice interprète"),
            MetierCourtDTO(id = "MET_586", "reporter-photographe / reportrice-photographe"),
            MetierCourtDTO(id = "MET_589", "biologiste en environnement"),
            MetierCourtDTO(id = "MET_588", "agent / agente de propreté urbaine"),
            MetierCourtDTO(id = "MET_550", "technicien / technicienne de forge"),
            MetierCourtDTO(id = "MET_552", "modéliste"),
            MetierCourtDTO(id = "MET_551", "architecte réseaux"),
            MetierCourtDTO(id = "MET_554", "technicien / technicienne de maintenance en informatique"),
            MetierCourtDTO(id = "MET_553", "technicien / technicienne de fabrication de mobilier et de menuiserie"),
            MetierCourtDTO(id = "MET_556", "secrétaire médical/e"),
            MetierCourtDTO(id = "MET_555", "manager de risques"),
            MetierCourtDTO(id = "MET_558", "notaire"),
            MetierCourtDTO(id = "MET_557", "professeur des écoles / professeure des écoles"),
            MetierCourtDTO(id = "MET_559", "toiletteur / toiletteuse d'animaux"),
            MetierCourtDTO(id = "MET_560", "verrier / verrière au chalumeau"),
            MetierCourtDTO(id = "MET_563", "archiviste"),
            MetierCourtDTO(id = "MET_562", "agent / agente de propreté et d'hygiène"),
            MetierCourtDTO(id = "MET_565", "officier / officière de la marine nationale"),
            MetierCourtDTO(id = "MET_564", "concepteur / conceptrice multimédia"),
            MetierCourtDTO(id = "MET_567", "officier / officière de l'armée de terre"),
            MetierCourtDTO(id = "MET_566", "maroquinier / maroquinière"),
            MetierCourtDTO(id = "MET_569", "éducateur/trice sportif/ve des activités aquatiques et de la natation"),
            MetierCourtDTO(id = "MET_568", "designer industriel / designeuse industrielle"),
            MetierCourtDTO(id = "MET_530", "animateur/trice handisport"),
            MetierCourtDTO(id = "MET_539", "chef / cheffe de produit marketing"),
            MetierCourtDTO(id = "MET_534", "femme / valet de chambre"),
            MetierCourtDTO(id = "MET_533", "graveur/euse sur métal"),
            MetierCourtDTO(id = "MET_536", "maquettiste"),
            MetierCourtDTO(id = "MET_535", "garçon / serveuse de café"),
            MetierCourtDTO(id = "MET_538", "plâtrier / plâtrière"),
            MetierCourtDTO(id = "MET_537", "directeur / directrice artistique"),
            MetierCourtDTO(id = "MET_541", "chef / cheffe des ventes"),
            MetierCourtDTO(id = "MET_540", "chargé / chargée d'études en marketing"),
            MetierCourtDTO(id = "MET_720", "cryptologue"),
            MetierCourtDTO(id = "MET_543", "responsable du service après-vente"),
            MetierCourtDTO(id = "MET_542", "directeur / directrice de magasin à grande surface"),
            MetierCourtDTO(id = "MET_545", "déclarant / déclarante en douane"),
            MetierCourtDTO(id = "MET_544", "directeur / directrice d'agence bancaire"),
            MetierCourtDTO(id = "MET_547", "agriculteur / agricultrice"),
            MetierCourtDTO(id = "MET_546", "déménageur / déménageuse"),
            MetierCourtDTO(id = "MET_549", "conducteur / conductrice de ligne de production alimentaire"),
            MetierCourtDTO(id = "MET_548", "technico-commercial / technico-commerciale en agroalimentaire"),
            MetierCourtDTO(id = "MET_518", "ingénieur en chef territorial / ingénieure en chef territoriale"),
            MetierCourtDTO(id = "MET_519", "knowledge manager"),
            MetierCourtDTO(id = "MET_510", "fromager / fromagère"),
            MetierCourtDTO(id = "MET_512", "data scientist"),
            MetierCourtDTO(id = "MET_511", "logisticien/ne de l'humanitaire"),
            MetierCourtDTO(id = "MET_514", "<span>Mosaïste d'art</span>"),
            MetierCourtDTO(id = "MET_513", "<span>Personnel de hall d'hôtel de luxe</span>"),
            MetierCourtDTO(id = "MET_515", "<span>Contrôleur / contrôleuse</span> <br> <span>des Finances publiques</span>"),
            MetierCourtDTO(id = "MET_528", "<span>Technicien / technicienne</span> <br> <span>en mécanique</span>"),
            MetierCourtDTO(id = "MET_523", "secrétaire de mairie"),
            MetierCourtDTO(id = "MET_522", "<span>Professeur / professeure de sport</span>"),
            MetierCourtDTO(id = "MET_527", "serrurier dépanneur / serrurière dépanneuse"),
            MetierCourtDTO(id = "MET_526", "designer transports"),
            MetierCourtDTO(id = "MET_738", "ingénieur/e chimiste en développement analytique"),
            MetierCourtDTO(id = "MET_737", "ingénieur/e radioprotection"),
            MetierCourtDTO(id = "MET_739", "responsable des ouvrages hydroélectriques"),
            MetierCourtDTO(id = "MET_730", "responsable approvisionnement"),
            MetierCourtDTO(id = "MET_732", "technicien démonstrateur / technicienne démonstratrice en matériel agricole"),
            MetierCourtDTO(id = "MET_731", "psychiatre"),
            MetierCourtDTO(id = "MET_733", "ingénieur / ingénieure logistique"),
            MetierCourtDTO(id = "MET_736", "spécialiste des affaires réglementaires en chimie"),
            MetierCourtDTO(id = "MET_749", "juriste en droit immobilier"),
            MetierCourtDTO(
                id = "MET_741",
                "conducteur / conductrice d'engins forestiers de récolte en entreprises de travaux forestiers",
            ),
            MetierCourtDTO(id = "MET_740", "conducteur/trice de machine onduleuse"),
            MetierCourtDTO(id = "MET_742", "généalogiste"),
            MetierCourtDTO(id = "MET_745", "designer automobile"),
            MetierCourtDTO(id = "MET_746", "<span>Perchman / perchwoman</span>"),
            MetierCourtDTO(id = "MET_716", "bactériologiste"),
            MetierCourtDTO(id = "MET_715", "chargé / chargée de recherche en acoustique musicale"),
            MetierCourtDTO(id = "MET_718", "architecte web"),
            MetierCourtDTO(id = "MET_703", "volcanologue"),
            MetierCourtDTO(id = "MET_717", "administrateur/trice de logiciels de laboratoire"),
            MetierCourtDTO(id = "MET_719", "prototypiste en matériaux souples"),
            MetierCourtDTO(id = "MET_710", "anesthésiste-réanimateur/trice"),
            MetierCourtDTO(id = "MET_712", "conseiller / conseillère pénitentiaire d'insertion et de probation"),
            MetierCourtDTO(id = "MET_711", "éducateur technique spécialisé / éducatrice technique spécialisée"),
            MetierCourtDTO(id = "MET_714", "coupeur/euse"),
            MetierCourtDTO(id = "MET_713", "directeur / directrice d'accueil collectif de mineurs (ACM)"),
            MetierCourtDTO(id = "MET_727", "ingénieur / ingénieure support"),
            MetierCourtDTO(id = "MET_726", "rudologue"),
            MetierCourtDTO(id = "MET_729", "auditeur / auditrice qualité"),
            MetierCourtDTO(id = "MET_728", "ingénieur / ingénieure en acoustique"),
            MetierCourtDTO(id = "MET_721", "ingénieur / ingénieure en caractérisation des matériaux"),
            MetierCourtDTO(id = "MET_723", "conseiller sportif / conseillère sportive en salle de remise en forme"),
            MetierCourtDTO(id = "MET_722", "technicien / technicienne céramiste"),
            MetierCourtDTO(id = "MET_725", "ingénieur / ingénieure fluides, énergies, réseaux, environnement"),
            MetierCourtDTO(id = "MET_724", "responsable de réseau eau potable"),
            MetierCourtDTO(id = "MET_705", "bûcheron/ne"),
            MetierCourtDTO(id = "MET_704", "arbitre"),
            MetierCourtDTO(id = "MET_707", "ingénieur / ingénieure logiciel"),
            MetierCourtDTO(id = "MET_706", "ingénieur / ingénieure en fonderie"),
            MetierCourtDTO(id = "MET_709", "géotechnicien / géotechnicienne"),
            MetierCourtDTO(id = "MET_708", "employé / employée de pressing"),
            MetierCourtDTO(id = "MET_701", "microbiologiste"),
            MetierCourtDTO(id = "MET_700", "gestionnaire de données cliniques"),
            MetierCourtDTO(id = "MET_702", "histologiste"),
            MetierCourtDTO(id = "MET_691", "officier / officière de gendarmerie"),
            MetierCourtDTO(id = "MET_693", "dessinateur / dessinatrice de BD"),
            MetierCourtDTO(id = "MET_692", "conservateur / conservatrice du patrimoine"),
            MetierCourtDTO(id = "MET_694", "teinturier/ère et blanchisseur/euse"),
            MetierCourtDTO(id = "MET_7778", "préposé / préposée au tir"),
            MetierCourtDTO(id = "MET_7776", "poseur / poseuse de voies ferrées"),
            MetierCourtDTO(id = "MET_7777", "électromécanicien/ne de chantier TP (travaux publics)"),
            MetierCourtDTO(id = "MET_697", "responsable des ressources humaines"),
            MetierCourtDTO(id = "MET_696", "chef / cheffe de projet multimédia"),
            MetierCourtDTO(id = "MET_699", "chercheur / chercheuse en biologie"),
            MetierCourtDTO(id = "MET_698", "grutier/ère"),
            MetierCourtDTO(id = "MET_222", "inspecteur / inspectrice de banque"),
            MetierCourtDTO(id = "MET_7772", "collaborateur / collaboratrice de cabinet d'expertise comptable"),
            MetierCourtDTO(id = "MET_7773", "sylviculteur/trice"),
            MetierCourtDTO(id = "MET_7767", "spécialiste en shiatsu"),
            MetierCourtDTO(id = "MET_7768", "couturier industriel / couturière industrielle"),
            MetierCourtDTO(id = "MET_7764", "technicien/ne de maintenance des matériels agricoles ou d'espaces verts"),
            MetierCourtDTO(id = "MET_7766", "chercheur/euse en robotique médicale"),
            MetierCourtDTO(id = "MET_671", "chargé / chargée de clientèle banque"),
            MetierCourtDTO(id = "MET_670", "secrétaire"),
            MetierCourtDTO(id = "MET_673", "commissaire-priseur / commissaire-priseuse"),
            MetierCourtDTO(id = "MET_672", "diététicien / diététicienne"),
            MetierCourtDTO(id = "MET_675", "ingénieur papetier / ingénieure papetière"),
            MetierCourtDTO(id = "MET_674", "matelot à la pêche"),
            MetierCourtDTO(id = "MET_677", "journaliste reporter d'images"),
            MetierCourtDTO(id = "MET_1291", "couvreur/euse tuilier"),
            MetierCourtDTO(id = "MET_1289", "couvreur/euse ardoisier/ière"),
            MetierCourtDTO(id = "MET_1288", "couvreur/euse photovoltaique"),
            MetierCourtDTO(id = "MET_676", "audioprothésiste"),
            MetierCourtDTO(id = "MET_679", "conducteur routier / conductrice routière"),
            MetierCourtDTO(id = "MET_678", "éditeur / éditrice"),
            MetierCourtDTO(id = "MET_680", "enseignant / enseignante de la conduite automobile et de la sécurité routière"),
            MetierCourtDTO(id = "MET_682", "maréchal-ferrant / maréchale-ferrante"),
            MetierCourtDTO(id = "MET_681", "bijoutier-joaillier / bijoutière-joaillière"),
            MetierCourtDTO(id = "MET_684", "régleur / régleuse"),
            MetierCourtDTO(id = "MET_683", "officier / officière de l'armée de l'air"),
            MetierCourtDTO(id = "MET_7748", "menuisier/ière aluminium-verre"),
            MetierCourtDTO(id = "MET_7744", "interprète français / LSF (langue des signes française)"),
            MetierCourtDTO(id = "MET_686", "mécanicien-outilleur / mécanicienne-outilleuse"),
            MetierCourtDTO(id = "MET_685", "mécanicien / mécanicienne bateaux"),
            MetierCourtDTO(id = "MET_688", "directeur / directrice d'hôpital"),
            MetierCourtDTO(id = "MET_1233", "livreur/euse"),
            MetierCourtDTO(id = "MET_1236", "scénariste de télévision"),
            MetierCourtDTO(id = "MET_1235", "scénariste de cinéma"),
            MetierCourtDTO(id = "MET_1238", "script doctor (consultant/e)"),
            MetierCourtDTO(id = "MET_1237", "scénariste multimédia"),
            MetierCourtDTO(id = "MET_1221", "sellier/ère bourrelier/ière"),
            MetierCourtDTO(id = "MET_687", "attaché / attachée d'administration"),
            MetierCourtDTO(id = "MET_653", "officier / officière de la marine marchande"),
            MetierCourtDTO(id = "MET_655", "employé / employée de restaurant"),
            MetierCourtDTO(id = "MET_654", "maître / maîtresse d'hôtel"),
            MetierCourtDTO(id = "MET_657", "chargé / chargée d'études média"),
            MetierCourtDTO(id = "MET_656", "chef monteur / cheffe monteuse"),
            MetierCourtDTO(id = "MET_659", "responsable de la promotion des ventes"),
            MetierCourtDTO(id = "MET_658", "solier-moquettiste / solière-moquettiste"),
            MetierCourtDTO(id = "MET_660", "gérant / gérante de portefeuille"),
            MetierCourtDTO(id = "MET_661", "analyste de crédit"),
            MetierCourtDTO(id = "MET_664", "technicien / technicienne automobile"),
            MetierCourtDTO(id = "MET_663", "affûteur / affûteuse"),
            MetierCourtDTO(id = "MET_666", "technicien / technicienne plasturgiste"),
            MetierCourtDTO(id = "MET_1222", "sellier/ère carrossier/ère"),
            MetierCourtDTO(id = "MET_1224", "sellier/ère harnacheur/euse"),
            MetierCourtDTO(id = "MET_1212", "facteur/trice d'instruments à vent"),
            MetierCourtDTO(id = "MET_665", "administrateur / administratrice réseaux"),
            MetierCourtDTO(id = "MET_668", "éducateur / éducatrice de jeunes enfants"),
            MetierCourtDTO(id = "MET_667", "chargé / chargée d'études économiques"),
            MetierCourtDTO(id = "MET_669", "conseiller / conseillère en économie sociale et familiale"),
            MetierCourtDTO(id = "MET_639", "ludothécaire"),
            MetierCourtDTO(id = "MET_638", "ingénieur / ingénieure de recherche (papiers-cartons)"),
            MetierCourtDTO(id = "MET_631", "vendeur/euse conseil caviste"),
            MetierCourtDTO(id = "MET_633", "ingénieur écoconcepteur / ingénieure écoconceptrice"),
            MetierCourtDTO(id = "MET_632", "expert / experte bilan carbone"),
            MetierCourtDTO(
                id = "MET_634",
                "psychologue de l'éducation nationale spécialité éducation, développement et " +
                        "conseil en orientation scolaire et professionnelle",
            ),
            MetierCourtDTO(id = "MET_636", "digital learning manager"),
            MetierCourtDTO(id = "MET_640", "retoucheur/euse"),
            MetierCourtDTO(id = "MET_649", "technicien/ne de contrôle"),
            MetierCourtDTO(id = "MET_39", "coiffeur / coiffeuse"),
            MetierCourtDTO(id = "MET_641", "<span>Fondeur / fondeuse</span>"),
            MetierCourtDTO(id = "MET_644", "consultant/e en communication"),
            MetierCourtDTO(id = "MET_643", "chargé/e d'études (urbanisme)"),
            MetierCourtDTO(id = "MET_646", "designer mobilier"),
            MetierCourtDTO(id = "MET_648", "assistant / assistante en architecture"),
            MetierCourtDTO(id = "MET_647", "moniteur/trice de voile"),
            MetierCourtDTO(id = "MET_859", "facteur / factrice d'instruments"),
            MetierCourtDTO(id = "MET_858", "chef / cheffe de projet packaging"),
            MetierCourtDTO(id = "MET_850", "peintre aéronautique"),
            MetierCourtDTO(id = "MET_854", "responsable e-commerce"),
            MetierCourtDTO(id = "MET_857", "vendeur/euse spécialisé/e en bricolage"),
            MetierCourtDTO(id = "MET_860", "vendeur / vendeuse en magasin"),
            MetierCourtDTO(id = "MET_869", "médecin généraliste"),
            MetierCourtDTO(id = "MET_862", "technicien / technicienne en lignes haute tension"),
            MetierCourtDTO(id = "MET_861", "actuaire"),
            MetierCourtDTO(id = "MET_864", "architecte naval / navale"),
            MetierCourtDTO(id = "MET_863", "ingénieur électronicien / ingénieure électronicienne"),
            MetierCourtDTO(id = "MET_1211", "facteur/trice de pianos"),
            MetierCourtDTO(id = "MET_1213", "facteur/trice d'orgues"),
            MetierCourtDTO(id = "MET_1218", "architecte programmiste"),
            MetierCourtDTO(id = "MET_1217", "architecte des Monuments historiques"),
            MetierCourtDTO(id = "MET_1219", "architecte et urbaniste de l'État"),
            MetierCourtDTO(id = "MET_1206", "visagiste"),
            MetierCourtDTO(id = "MET_866", "technicien / technicienne de maintenance industrielle"),
            MetierCourtDTO(id = "MET_865", "contrôleur / contrôleuse de performance"),
            MetierCourtDTO(id = "MET_868", "préparateur / préparatrice en pharmacie"),
            MetierCourtDTO(id = "MET_867", "gestionnaire de contrats d'assurance"),
            MetierCourtDTO(id = "MET_837", "<span>Gardien / gardienne d'immeubles</span>"),
            MetierCourtDTO(id = "MET_839", "moniteur/trice de tennis"),
            MetierCourtDTO(id = "MET_831", "inséminateur / inséminatrice"),
            MetierCourtDTO(id = "MET_830", "responsable des produits structurés actions"),
            MetierCourtDTO(id = "MET_832", "pisteur / pisteuse secouriste"),
            MetierCourtDTO(id = "MET_840", "directeur/trice des ventes"),
            MetierCourtDTO(id = "MET_842", "responsable du soutien logistique intégré"),
            MetierCourtDTO(id = "MET_844", "ingénieur / ingénieure de recherche clinique et épidémiologique"),
            MetierCourtDTO(id = "MET_843", "ingénieur / ingénieure production dans les biotechnologies"),
            MetierCourtDTO(id = "MET_845", "gynécologue-obstétricien/ne"),
            MetierCourtDTO(id = "MET_40", "gouvernante"),
            MetierCourtDTO(id = "MET_1209", "facteur/trice d'accordéons"),
            MetierCourtDTO(id = "MET_815", "gestionnaire actif / passif"),
            MetierCourtDTO(id = "MET_38", "infirmier / infirmière"),
            MetierCourtDTO(id = "MET_814", "web-ergonome"),
            MetierCourtDTO(id = "MET_817", "enquêteur privé / enquêtrice privée"),
            MetierCourtDTO(id = "MET_816", "administrateur / administratrice de mission humanitaire"),
            MetierCourtDTO(id = "MET_819", "secrétaire juridique"),
            MetierCourtDTO(id = "MET_818", "mandataire judiciaire"),
            MetierCourtDTO(id = "MET_31", "cartographe"),
            MetierCourtDTO(id = "MET_30", "responsable de formation"),
            MetierCourtDTO(id = "MET_33", "avocat / avocate"),
            MetierCourtDTO(id = "MET_32", "ingénieur opticien / ingénieure opticienne"),
            MetierCourtDTO(id = "MET_35", "technicien / technicienne des industries du verre"),
            MetierCourtDTO(id = "MET_34", "mouleur-noyauteur / mouleuse-noyauteuse"),
            MetierCourtDTO(id = "MET_829", "glaciologue"),
            MetierCourtDTO(id = "MET_810", "démineur/euse"),
            MetierCourtDTO(id = "MET_813", "roboticien/ne"),
            MetierCourtDTO(id = "MET_37", "conducteur / conductrice de machines à papier"),
            MetierCourtDTO(id = "MET_812", "biologiste médical/e"),
            MetierCourtDTO(id = "MET_36", "technicien / technicienne chimiste"),
            MetierCourtDTO(id = "MET_51", "professeur / professeure de collège et de lycée"),
            MetierCourtDTO(id = "MET_50", "ouvrier forestier / ouvrière forestière"),
            MetierCourtDTO(id = "MET_826", "ingénieur/e technico-commercial en chimie"),
            MetierCourtDTO(id = "MET_49", "constructeur / constructrice de réseaux de canalisations"),
            MetierCourtDTO(id = "MET_825", "consultant/e en validation"),
            MetierCourtDTO(id = "MET_828", "rédacteur médical / rédactrice médicale"),
            MetierCourtDTO(id = "MET_827", "coordonnateur/trice d'études cliniques"),
            MetierCourtDTO(id = "MET_1208", "archetier/ère"),
            MetierCourtDTO(id = "MET_42", "danseur / danseuse"),
            MetierCourtDTO(id = "MET_41", "accompagnateur / accompagnatrice de voyages"),
        )
        return MetiersCourtsDTO(
            metiers = metiers.filter { it.nom.contains(recherche, true) },
        )
    }

    @GetMapping("/recherche/detaillee")
    fun getRechercheMetierDetaillee(
        @RequestParam recherche: String,
    ): MetiersDTO {
        val metiers = listOf(
            MetierDTO(
                id = "MET_319",
                nom = "<span>Assistant / assistante de direction</span>",
                descriptif =
                "Pour seconder la direction d'une entreprise, l'assistante ou l'assistant de direction exerce des " +
                        "missions variées, de la prise de rendez-vous à l'organisation de déplacements ou de réunions en passant " +
                        "par le filtrage des appels ou la réception des clients. Un poste à responsabilités.<br/><br/><h3>Après " +
                        "le bac</h3><p>2 ans pour préparer le BTS support à l'action managériale.</p>",
                liens =
                listOf(
                    LienDTO(
                        nom = "<span>Assistant / assistante de direction</span>",
                        url = "https://explorer-avenirs.onisep.fr/http/redirection/metier/slug/MET.319",
                    ),
                ),
            ),
            MetierDTO(
                id = "MET_312",
                nom = "moniteur/trice de ski",
                descriptif =
                "<p>Amoureux de la montagne et sportif émérite, le moniteur de ski évolue dans un cadre de rêve et " +
                        "transmet sa passion aux vacanciers débutants comme experts. Mais il doit composer avec la concurrence et " +
                        "le caractère saisonnier de son activité.</p>",
                liens =
                listOf(
                    LienDTO(
                        nom = "Éducation en activités sportives",
                        url = "https://candidat.pole-emploi.fr/marche-du-travail/fichemetierrome?codeRome=G1204",
                    ),
                    LienDTO(
                        nom = "\"moniteur / monitrice de ski",
                        url = "https://explorer-avenirs.onisep.fr/http/redirection/metier/slug/MET.312",
                    ),
                ),
            ),
            MetierDTO(
                id = "MET_311",
                nom = "éducateur spécialisé / éducatrice spécialisée",
                descriptif =
                "<p>L'éducateur spécialisé aide des personnes en situation de handicap ou en difficulté à devenir " +
                        "autonomes. Avec une double mission : contribuer à leur épanouissement personnel et à leur insertion " +
                        "en société.</p>",
                liens =
                listOf(
                    LienDTO(
                        nom = "Intervention socioéducative",
                        url = "https://candidat.pole-emploi.fr/marche-du-travail/fichemetierrome?codeRome=K1207",
                    ),
                    LienDTO(
                        nom = "éducateur spécialisé / éducatrice spécialisée",
                        url = "https://explorer-avenirs.onisep.fr/http/redirection/metier/slug/MET.311",
                    ),
                ),
            ),
        )
        return MetiersDTO(
            metiers.filter {
                (it.nom.contains(recherche, true)
                        || it.descriptif?.contains(recherche, true) == true) || it.liens.map { it.nom }.any { it.contains(recherche, true) }
            },
        )
    }
}
