/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/profil": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getProfilEleve"];
    put?: never;
    post: operations["postProfilEleve"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/formations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["getFormations"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/formations/{idformation}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postFormation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/formations/suggestions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["postSuggestionsFormations"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/referentiel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getReferentielPourInscription"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/metiers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getMetiers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/metiers/recherche/succincte": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getRechercheMetierSuccincte"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/formations/recherche/succincte": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getRechercheFormationSuccincte"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/formations/recherche/detaillee": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getRechercheFormationDetaillee"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CommuneDTO: {
      /**
       * @description Code Insee de la ville
       * @example 75015
       */
      codeInsee: string;
      /**
       * @description Dénomination de la ville
       * @example Paris
       */
      nom: string;
      /**
       * Format: float
       * @description Latitude de la ville
       * @example 48.8512252
       */
      latitude: number;
      /**
       * Format: float
       * @description Longitude de la ville
       * @example 2.2885659
       */
      longitude: number;
    };
    ProfilDTO: {
      /**
       * @description Id de l'élève
       * @example adcf627c-36dd-4df5-897b-159443a6d49c
       */
      id: string;
      /**
       * @description Etat d'avancée du projet de l'élève
       * @example aucune_idee
       * @enum {string}
       */
      situation?: "aucune_idee" | "quelques_pistes" | "projet_precis";
      /**
       * @description Classe actuelle
       * @example terminale
       * @enum {string}
       */
      classe?: "seconde" | "premiere" | "terminale";
      /**
       * @description Type de Bac choisi ou envisagé
       * @example Générale
       * @enum {string}
       */
      baccalaureat?:
        | "NC"
        | "Générale"
        | "P"
        | "PA"
        | "S2TMD"
        | "ST2S"
        | "STAV"
        | "STD2A"
        | "STHR"
        | "STI2D"
        | "STL"
        | "STMG";
      /**
       * @description Enseignements de spécialité de terminale choisis ou envisagés
       * @example [
       *       "1056",
       *       "1054"
       *     ]
       */
      specialites?: string[];
      /**
       * @description Domaines d'activité
       * @example [
       *       "T_ITM_1054",
       *       "T_ITM_1534",
       *       "T_ITM_1248",
       *       "T_ITM_1351"
       *     ]
       */
      domaines?: string[];
      /**
       * @description Centres d'intérêt
       * @example [
       *       "T_ROME_2092381917",
       *       "T_IDEO2_4812"
       *     ]
       */
      centresInterets?: string[];
      /**
       * @description Les idées de métiers de l'élève
       * @example [
       *       "MET_123",
       *       "MET_456"
       *     ]
       */
      metiersFavoris?: string[];
      /**
       * @description Durée envisagée des études
       * @example indifferent
       * @enum {string}
       */
      dureeEtudesPrevue?: "indifferent" | "courte" | "longue" | "aucune_idee";
      /**
       * @description Intérêt pour les formations en apprentissage
       * @example pas_interesse
       * @enum {string}
       */
      alternance?: "pas_interesse" | "indifferent" | "interesse" | "tres_interesse";
      /**
       * @description Villes préférées pour étudier
       */
      communesFavorites?: Array<components["schemas"]["CommuneDTO"]>;
      /**
       * Format: float
       * @description Moyenne générale scolaire estimée en terminale
       * @example 14
       */
      moyenneGenerale?: number;
      /**
       * @description Les idées de formations de l'élève
       * @example [
       *       "fl1234",
       *       "fl5678"
       *     ]
       */
      formationsFavorites?: string[];
    };
    ResponseBody: Record<string, never>;
    ProfilObligatoireRequeteDTO: {
      profil: components["schemas"]["ProfilDTO"];
    };
    AffiniteSpecialiteDTO: {
      nomSpecialite: string;
      /**
       * Format: int32
       */
      pourcentage: number;
    };
    AutoEvaluationMoyenneDTO: {
      /**
       * Format: float
       */
      moyenne: number;
      /**
       * Format: float
       */
      basIntervalleNotes: number;
      /**
       * Format: float
       */
      hautIntervalleNotes: number;
      baccalaureatUtilise: components["schemas"]["BaccalaureatDTO"];
    };
    BaccalaureatDTO: {
      id: string;
      nom: string;
    };
    CentileDTO: {
      /**
       * Format: int32
       */
      centile: number;
      /**
       * Format: float
       */
      note: number;
    };
    CriteresAnalyseCandidatureDTO: {
      nom: string;
      /**
       * Format: int32
       */
      pourcentage: number;
    };
    DomaineDTO: {
      id: string;
      nom: string;
      emoji: string;
    };
    ExplicationGeographiqueDTO: {
      nomVille: string;
      /**
       * Format: int32
       */
      distanceKm: number;
    };
    ExplicationsDTO: {
      geographique: Array<components["schemas"]["ExplicationGeographiqueDTO"]>;
      formationsSimilaires: Array<components["schemas"]["FormationSimilaireDTO"]>;
      dureeEtudesPrevue?: string;
      alternance?: string;
      interetsEtDomainesChoisis?: components["schemas"]["InteretsEtDomainesDTO"];
      specialitesChoisies: Array<components["schemas"]["AffiniteSpecialiteDTO"]>;
      typeBaccalaureat?: components["schemas"]["TypeBaccalaureatDTO"];
      autoEvaluationMoyenne?: components["schemas"]["AutoEvaluationMoyenneDTO"];
    };
    FicheFormationDTO: {
      id: string;
      nom: string;
      idsFormationsAssociees: string[];
      descriptifFormation?: string;
      descriptifDiplome?: string;
      descriptifConseils?: string;
      descriptifAttendus?: string;
      moyenneGeneraleDesAdmis?: components["schemas"]["MoyenneGeneraleDesAdmisDTO"];
      criteresAnalyseCandidature: Array<components["schemas"]["CriteresAnalyseCandidatureDTO"]>;
      repartitionAdmisAnneePrecedente?: components["schemas"]["RepartitionAdmisAnneePrecedenteDTO"];
      liens: Array<components["schemas"]["LienDTO"]>;
      villes: string[];
      metiers: Array<components["schemas"]["MetierDTO"]>;
      /**
       * Format: int32
       */
      tauxAffinite?: number;
    };
    FormationAvecExplicationsDTO: {
      formation: components["schemas"]["FicheFormationDTO"];
      explications?: components["schemas"]["ExplicationsDTO"];
    };
    FormationSimilaireDTO: {
      id: string;
      nom: string;
    };
    FormationsAvecExplicationsDTO: {
      formations: Array<components["schemas"]["FormationAvecExplicationsDTO"]>;
    };
    InteretDTO: {
      id: string;
      nom: string;
    };
    InteretsEtDomainesDTO: {
      interets: Array<components["schemas"]["InteretDTO"]>;
      domaines: Array<components["schemas"]["DomaineDTO"]>;
    };
    LienDTO: {
      nom: string;
      url: string;
    };
    MetierDTO: {
      id: string;
      nom: string;
      descriptif?: string;
      liens: Array<components["schemas"]["LienDTO"]>;
    };
    MoyenneGeneraleDesAdmisDTO: {
      baccalaureat?: components["schemas"]["BaccalaureatDTO"];
      centiles: Array<components["schemas"]["CentileDTO"]>;
    };
    RepartitionAdmisAnneePrecedenteDTO: {
      /**
       * Format: int32
       */
      total: number;
      parBaccalaureat: Array<components["schemas"]["TotalAdmisPourUnBaccalaureatDTO"]>;
    };
    TotalAdmisPourUnBaccalaureatDTO: {
      baccalaureat: components["schemas"]["BaccalaureatDTO"];
      /**
       * Format: int32
       */
      nombreAdmis: number;
    };
    TypeBaccalaureatDTO: {
      baccalaureat: components["schemas"]["BaccalaureatDTO"];
      /**
       * Format: int32
       */
      pourcentage: number;
    };
    ProfilOptionnelRequeteDTO: {
      profil?: components["schemas"]["ProfilDTO"];
    };
    BaccalaureatAvecSesSpecialitesDTO: {
      baccalaureat: components["schemas"]["BaccalaureatDTO"];
      specialites: Array<components["schemas"]["SpecialitesDTO"]>;
    };
    CategorieDomaineAvecDomainesDTO: {
      categorieDomaine: components["schemas"]["CategorieDomaineDTO"];
      domaines: Array<components["schemas"]["DomaineDTO"]>;
    };
    CategorieDomaineDTO: {
      id: string;
      nom: string;
      emoji: string;
    };
    CategorieInteretAevcSousCategoriesDTO: {
      categorieInteret: components["schemas"]["InteretCategorieDTO"];
      sousCategoriesInterets: Array<components["schemas"]["InteretSousCategorieDTO"]>;
    };
    InteretCategorieDTO: {
      id: string;
      nom: string;
      emoji: string;
    };
    InteretSousCategorieDTO: {
      id: string;
      nom: string;
      emoji: string;
    };
    ReferentielDTO: {
      situations: string[];
      choixNiveau: string[];
      choixAlternance: string[];
      choixDureeEtudesPrevue: string[];
      baccalaureatsAvecLeurSpecialites: Array<components["schemas"]["BaccalaureatAvecSesSpecialitesDTO"]>;
      categoriesDInteretsAvecLeursSousCategories: Array<components["schemas"]["CategorieInteretAevcSousCategoriesDTO"]>;
      categoriesDomaineAvecLeursDomaines: Array<components["schemas"]["CategorieDomaineAvecDomainesDTO"]>;
    };
    SpecialitesDTO: {
      id: string;
      nom: string;
    };
    MetiersDTO: {
      metiers: Array<components["schemas"]["MetierDTO"]>;
    };
    MetierCourtDTO: {
      id: string;
      nom: string;
    };
    MetiersCourtsDTO: {
      metiers: Array<components["schemas"]["MetierCourtDTO"]>;
    };
    FormationCourteDTO: {
      id: string;
      nom: string;
    };
    FormationsCourtesDTO: {
      formations: Array<components["schemas"]["FormationCourteDTO"]>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getProfilEleve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description OK
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ProfilDTO"];
        };
      };
    };
  };
  postProfilEleve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfilDTO"];
      };
    };
    responses: {
      /**
       * @description OK
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ResponseBody"];
        };
      };
    };
  };
  getFormations: {
    parameters: {
      query: {
        ids: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfilObligatoireRequeteDTO"];
      };
    };
    responses: {
      /**
       * @description OK
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["FormationsAvecExplicationsDTO"];
        };
      };
    };
  };
  postFormation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        idformation: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfilOptionnelRequeteDTO"];
      };
    };
    responses: {
      /**
       * @description OK
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["FormationAvecExplicationsDTO"];
        };
      };
    };
  };
  postSuggestionsFormations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfilObligatoireRequeteDTO"];
      };
    };
    responses: {
      /**
       * @description OK
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["FormationsAvecExplicationsDTO"];
        };
      };
    };
  };
  getReferentielPourInscription: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description OK
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ReferentielDTO"];
        };
      };
    };
  };
  getMetiers: {
    parameters: {
      query: {
        ids: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description OK
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["MetiersDTO"];
        };
      };
    };
  };
  getRechercheMetierSuccincte: {
    parameters: {
      query: {
        recherche: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description OK
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["MetiersCourtsDTO"];
        };
      };
    };
  };
  getRechercheFormationSuccincte: {
    parameters: {
      query: {
        recherche: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description OK
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["FormationsCourtesDTO"];
        };
      };
    };
  };
  getRechercheFormationDetaillee: {
    parameters: {
      query: {
        recherche: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /**
       * @description OK
       */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["FormationsAvecExplicationsDTO"];
        };
      };
    };
  };
}
