name: "Setup Node and packages"
inputs:
  node-version:
    required: true
runs:
  using: "composite"
  steps:
    - name: Use Node.js LTS
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'
        cache-dependency-path: '${{ env.WORKING_DIRECTORY }}/package-lock.json'

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: ${{ env.WORKING_DIRECTORY }}/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(format('{0}/package-lock.json', env.WORKING_DIRECTORY)) }}
