name: (Backend) Lint & Tests

on:
  workflow_call:

env:
  WORKING_DIRECTORY: ./app/back

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4
      - name: Run lint command
        run: mvn ktlint:check

  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'
      - name: Run test command
        run: mvn test
        env:
          APP_DB_HOST_NAME: localhost
          APP_DB_NAME: postgres
          APP_DB_USER: postgres
          APP_DB_PASSWORD: postgres
          APP_DB_PORT: 5432
          SERVER_PORT: 5002
          DB_URL: jdbc:postgresql://localhost:5432/postgres
          DB_USER: postgres
          DB_PASSWORD: postgres
          CORS_ORIGINPATTERNS: http://appfront:5001,http://localhost:5002
          SUGGESTIONS_API_URL: http://localhost:8004/api/1.2
          KEYCLOAK_CLIENT_ID: mps-cli
          KEYCLOAK_CLIENT_SECRET: anfoYhY7PNxIhgEthcWdbq2P4XPJ90Aw
          KEYCLOAK_ROYAUME_URL: http://localhost:5003/realms/avenirs
          KEYCLOAK_ROYAUME_URL_JWT_VERIF: http://localhost:5003/realms/avenirs
