name: Pull Request Etl

on:
  pull_request:
    paths:
      - 'app/etl/**'
      - '.github/**'

jobs:

  checkEtl:
    name: Etl
    uses: ./.github/workflows/etl.yml
    secrets:
      DATA_REPOSITORY: "${{ secrets.DATA_REPOSITORY }}"