name: Pull Request Etl

on:
  pull_request:
    paths:
      - 'app/etl/**'
      - '.github/**'

jobs:

  checkEtl:
    name: Etl
    uses: ./.github/workflows/etl.yml
    secrets:
      DATA_REPOSITORY: "${{ secrets.DATA_REPOSITORY }}"
      MPS_DATA_GOOGLE_API_KEY: "${{ secrets.MPS_DATA_GOOGLE_API_KEY }}"
      MPS_DATA_GOOGLE_API_SPREADSHEET_ID: "${{ secrets.MPS_DATA_GOOGLE_API_SPREADSHEET_ID }}"