name: (Suggestions) Lint & Tests

on:
  workflow_call:
    secrets:
      DATA_REPOSITORY:
        required: true

env:
  WORKING_DIRECTORY: ./app/suggestions
  APP_DB: postgres
  APP_DB_USERNAME: postgres
  APP_DB_PASSWORD: postgres
  APP_DB_PORT: 5432
  JAVA_VENDOR: temurin
  JAVA_VERSION: 21

jobs:
  lint:
    name: Linters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4
      - name: Run lint command
        run: mvn ktlint:check

  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      MPS_DATA_DIR: ${{ runner.temp }}/mps_data
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ${{ env.APP_DB }}
          POSTGRES_USER: ${{ env.APP_DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.APP_DB_PASSWORD }}
          PGPORT: ${{ env.APP_DB_PORT }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: '${{ env.JAVA_VENDOR }}' 
          java-version: '${{ env.JAVA_VERSION }}'

      - name: Fetch data Repository
        run: |
          mkdir -p ${{ runner.temp }}/mps_data
          git clone --depth 1 ${{ secrets.DATA_REPOSITORY }} $MPS_DATA_DIR

      - name: Install etl-common depedency
        run: mvn -f ../etl/pom.xml clean compile install -DskipTests=true

      - name: Initialize test db with reference data
        run: mvn -f ../etl/pom.xml clean compile -f../etl/etl-updatedb/pom.xml exec:java -Dexec.mainClass=fr.gouv.monprojetsup.data.etl.UpdateMpsDbKt
        env:
          DB_URL: jdbc:postgresql://localhost:${{ env.APP_DB_PORT }}/${{ env.APP_DB }}
          DB_USER: ${{ env.APP_DB_USERNAME }}
          DB_PASSWORD: ${{ env.APP_DB_PASSWORD }}
	  
      - name: Run test command
        run: mvn test
        env:
          DB_URL: jdbc:postgresql://localhost:${{ env.APP_DB_PORT }}/${{ env.APP_DB }}
          DB_USER: ${{ env.APP_DB_USERNAME }}
          DB_PASSWORD: ${{ env.APP_DB_PASSWORD }}




